package org.dy.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2015-11-29T16:48:34.937+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.ws.dy.org/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWorldsByUser", targetNamespace = "http://service.ws.dy.org/", className = "org.dy.ws.service.GetWorldsByUser")
    @WebMethod
    @ResponseWrapper(localName = "getWorldsByUserResponse", targetNamespace = "http://service.ws.dy.org/", className = "org.dy.ws.service.GetWorldsByUserResponse")
    public java.util.List<org.dy.ws.service.World> getWorldsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        org.dy.ws.service.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllWorlds2", targetNamespace = "http://service.ws.dy.org/", className = "org.dy.ws.service.GetAllWorlds2")
    @WebMethod
    @ResponseWrapper(localName = "getAllWorlds2Response", targetNamespace = "http://service.ws.dy.org/", className = "org.dy.ws.service.GetAllWorlds2Response")
    public org.dy.ws.service.WorldMap getAllWorlds2();

    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "getAllWorlds", targetNamespace = "http://service.ws.dy.org/", className = "org.dy.ws.service.GetAllWorlds")
    @WebMethod
    @ResponseWrapper(localName = "getAllWorldsResponse", targetNamespace = "http://service.ws.dy.org/", className = "org.dy.ws.service.GetAllWorldsResponse")
    public org.dy.ws.service.GetAllWorldsResponse.Return getAllWorlds();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.ws.dy.org/", className = "org.dy.ws.service.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.ws.dy.org/", className = "org.dy.ws.service.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
