package org.dy.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2015-11-27T23:34:55.879+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.ws.dy.org/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWorldsByUser", targetNamespace = "http://service.ws.dy.org/", className = "org.dy.ws.service.GetWorldsByUser")
    @WebMethod
    @ResponseWrapper(localName = "getWorldsByUserResponse", targetNamespace = "http://service.ws.dy.org/", className = "org.dy.ws.service.GetWorldsByUserResponse")
    public java.util.List<org.dy.ws.service.World> getWorldsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        org.dy.ws.service.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.ws.dy.org/", className = "org.dy.ws.service.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.ws.dy.org/", className = "org.dy.ws.service.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
