package helloworldws.impl.service.ws.dy.org;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.dy.ws.service.HelloWorld;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2015-11-29T15:28:41.282+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "HelloWorldWS", 
                  wsdlLocation = "http://localhost:9999/helloworldws?wsdl",
                  targetNamespace = "org.dy.ws.service.impl.HelloWorldWS") 
public class HelloWorldWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("org.dy.ws.service.impl.HelloWorldWS", "HelloWorldWS");
    public final static QName HelloWorldWSPort = new QName("org.dy.ws.service.impl.HelloWorldWS", "HelloWorldWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9999/helloworldws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorldWS.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9999/helloworldws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldWS() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorldWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorldWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorldWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldWSPort")
    public HelloWorld getHelloWorldWSPort() {
        return super.getPort(HelloWorldWSPort, HelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldWSPort")
    public HelloWorld getHelloWorldWSPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldWSPort, HelloWorld.class, features);
    }

}
